from dataclasses import dataclass
from pathlib import Path


def read_lines(filepath: Path) -> str:
    return [*filepath.read_text().splitlines(), ""]


@dataclass
class StatBlockTestCase:
    beast: str
    stats: dict[str, int | str]
    statblock_class: list[str]


amoeba = StatBlockTestCase(
    beast="Amoeba",
    stats={
        "": {
            "Basic Profile": {
                "M": 4,
                "WS": 33,
                "BS": 0,
                "S": 3,
                "T": 5,
                "W": 11,
                "I": 30,
                "A": 3,
                "Dex": 0,
                "Ld": 0,
                "Int": 0,
                "Cl": 0,
                "WP": 0,
                "Fel": 0,
            },
        },
    },
    statblock_class=[
        "class Amoeba(Warhammer):",
        "    M = 4",
        "    WS = 33",
        "    BS = 0",
        "    S = 3",
        "    T = 5",
        "    W = 11",
        "    I = 30",
        "    A = 3",
        "    Dex = 0",
        "    Ld = 0",
        "    Int = 0",
        "    Cl = 0",
        "    WP = 0",
        "    Fel = 0",
        "",
    ],
)

bat = StatBlockTestCase(
    beast="Bat",
    stats={
        "": {
            "Basic Profile": {
                "M": 0,
                "WS": 59,
                "BS": 0,
                "S": 0,
                "T": 1,
                "W": 1,
                "I": 30,
                "A": 1,
                "Dex": 0,
                "Ld": 14,
                "Int": 5,
                "Cl": 29,
                "WP": 29,
                "Fel": 0,
            },
        },
    },
    statblock_class=[],
)

horse = StatBlockTestCase(
    beast="Horse",
    stats={
        "M": 8,
        "WS": 33,
        "BS": 0,
        "S": "2-5",
        "T": 3,
        "W": "5/11",
        "I": 30,
        "A": "0/1",
        "Dex": 0,
        "Ld": 10,
        "Int": 10,
        "Cl": 10,
        "WP": 10,
        "Fel": 0,
    },
    statblock_class=[
        "class Horse(Warhammer):",
        "    M = 8",
        "    WS = 33",
        "    BS = 0",
        "    S = 2",
        "    T = 3",
        "    W = 5",
        "    I = 30",
        "    A = 0",
        "    Dex = 0",
        "    Ld = 10",
        "    Int = 10",
        "    Cl = 10",
        "    WP = 10",
        "    Fel = 0",
        "",
    ],
)

beast_of_nurgle = StatBlockTestCase(
    beast="Beast Of Nurgle",
    stats={
        "": {
            "Basic Profile": {
                "M": 3,
                "WS": 30,
                "BS": 0,
                "S": 3,
                "T": 5,
                "W": 15,
                "I": 30,
                "A": "D6",
                "Dex": 6,
                "Ld": 24,
                "Int": 10,
                "Cl": 89,
                "WP": 98,
                "Fel": 0,
            },
        },
    },
    statblock_class=read_lines(Path("tests/assets/beast_of_nurgle.py").absolute()),
)

artisans_apprentice = StatBlockTestCase(
    beast="Artisan's Apprentice",
    stats={
        "": {
            "Basic Profile": {
                "M": 4,
                "WS": 31,
                "BS": 25,
                "S": 3,
                "T": 3,
                "W": 6,
                "I": 40,
                "A": 1,
                "Dex": 39,
                "Ld": 29,
                "Int": 29,
                "Cl": 29,
                "WP": 29,
                "Fel": 29,
            },
        },
    },
    statblock_class=read_lines(Path("tests/assets/artisans_apprentice.py").absolute()),
)

thugs = StatBlockTestCase(
    beast="Thugs",
    stats={
        "Thug": {
            "Basic Profile": {
                "M": 4,
                "WS": 31,
                "BS": 25,
                "S": 3,
                "T": 4,
                "W": 7,
                "I": 30,
                "A": 1,
                "Dex": 29,
                "Ld": 29,
                "Int": 29,
                "Cl": 29,
                "WP": 29,
                "Fel": 29,
            },
        },
        "Teamsters or Stevedores": {
            "Basic Profile": {
                "M": 4,
                "WS": 33,
                "BS": 25,
                "S": 3,
                "T": 4,
                "W": 8,
                "I": 30,
                "A": 1,
                "Dex": 34,
                "Ld": 28,
                "Int": 33,
                "Cl": 30,
                "WP": 32,
                "Fel": 29,
            },
        },
    },
    statblock_class=[
        "class Thugs:",
        "    class Thug(Warhammer):",
        "        M = 4",
        "        WS = 31",
        "        BS = 25",
        "        S = 3",
        "        T = 4",
        "        W = 7",
        "        I = 30",
        "        A = 1",
        "        Dex = 29",
        "        Ld = 29",
        "        Int = 29",
        "        Cl = 29",
        "        WP = 29",
        "        Fel = 29",
        "",
        "    class Teamsters_or_Stevedores(Warhammer):",
        "        M = 4",
        "        WS = 33",
        "        BS = 25",
        "        S = 3",
        "        T = 4",
        "        W = 8",
        "        I = 30",
        "        A = 1",
        "        Dex = 34",
        "        Ld = 28",
        "        Int = 33",
        "        Cl = 30",
        "        WP = 32",
        "        Fel = 29",
        "",
    ],
)

soldiers = StatBlockTestCase(
    beast="Soldiers",
    stats={
        "Generic Soldier": {
            "Basic Profile": {
                "M": 4,
                "WS": 43,
                "BS": 35,
                "S": 3,
                "T": 3,
                "W": 8,
                "I": 40,
                "A": 1,
                "Dex": 29,
                "Ld": 39,
                "Int": 29,
                "Cl": 29,
                "WP": 29,
                "Fel": 29,
            },
        },
        "The Imperial Guard": {
            "Cavalry Officer": {
                "M": 4,
                "WS": 65,
                "BS": 50,
                "S": 5,
                "T": 5,
                "W": 13,
                "I": 50,
                "A": 3,
                "Dex": 49,
                "Ld": 69,
                "Int": 39,
                "Cl": 69,
                "WP": 40,
                "Fel": 50,
            },
            "Cavalryman": {
                "M": 4,
                "WS": 50,
                "BS": 38,
                "S": 4,
                "T": 4,
                "W": 11,
                "I": 50,
                "A": 3,
                "Dex": 39,
                "Ld": 39,
                "Int": 29,
                "Cl": 40,
                "WP": 29,
                "Fel": 30,
            },
            "Officer": {
                "M": 4,
                "WS": 60,
                "BS": 45,
                "S": 5,
                "T": 5,
                "W": 13,
                "I": 60,
                "A": 3,
                "Dex": 49,
                "Ld": 69,
                "Int": 40,
                "Cl": 60,
                "WP": 40,
                "Fel": 50,
            },
            "Soldier": {
                "M": 4,
                "WS": "50♦",
                "BS": "40♦",
                "S": 4,
                "T": 4,
                "W": 11,
                "I": 50,
                "A": 2,
                "Dex": 39,
                "Ld": 39,
                "Int": 29,
                "Cl": 40,
                "WP": 29,
                "Fel": 30,
            },
            "Mercenary Captain": {
                "M": 4,
                "WS": 55,
                "BS": 45,
                "S": 4,
                "T": 4,
                "W": 11,
                "I": 55,
                "A": 2,
                "Dex": 39,
                "Ld": 55,
                "Int": 39,
                "Cl": 50,
                "WP": 35,
                "Fel": 45,
            },
            "Mercenary Soldier": {
                "M": 4,
                "WS": 45,
                "BS": 35,
                "S": 3,
                "T": 4,
                "W": 8,
                "I": 45,
                "A": 2,
                "Dex": 29,
                "Ld": 39,
                "Int": 29,
                "Cl": 35,
                "WP": 25,
                "Fel": 30,
            },
            "Templar": {
                "M": 4,
                "WS": 70,
                "BS": 55,
                "S": 5,
                "T": 5,
                "W": 15,
                "I": 70,
                "A": 3,
                "Dex": 59,
                "Ld": 59,
                "Int": 50,
                "Cl": 65,
                "WP": 60,
                "Fel": 59,
            },
            "Halfling Infantry": {
                "M": 3,
                "WS": 38,
                "BS": 45,
                "S": 3,
                "T": 3,
                "W": 8,
                "I": 60,
                "A": 2,
                "Dex": 49,
                "Ld": 30,
                "Int": 29,
                "Cl": 34,
                "WP": 55,
                "Fel": 53,
            },
        },
        "Standing Armies In The Empire": {
            "Sergeant": {
                "M": 4,
                "WS": 50,
                "BS": 30,
                "S": 4,
                "T": 4,
                "W": 11,
                "I": 50,
                "A": 2,
                "Dex": 39,
                "Ld": 55,
                "Int": 40,
                "Cl": 50,
                "WP": 35,
                "Fel": 40,
            },
            "Soldier": {
                "M": 4,
                "WS": 45,
                "BS": 30,
                "S": 3,
                "T": 3,
                "W": 7,
                "I": 40,
                "A": 1,
                "Dex": 29,
                "Ld": 39,
                "Int": 29,
                "Cl": 29,
                "WP": 25,
                "Fel": 30,
            },
            "Pikeman": {
                "M": 4,
                "WS": 45,
                "BS": 30,
                "S": 3,
                "T": 3,
                "W": 7,
                "I": 40,
                "A": 1,
                "Dex": 29,
                "Ld": 40,
                "Int": 29,
                "Cl": 30,
                "WP": 26,
                "Fel": 29,
            },
            "Mercenary Crossbowman": {
                "M": 4,
                "WS": 40,
                "BS": 50,
                "S": 3,
                "T": 4,
                "W": 9,
                "I": 45,
                "A": 2,
                "Dex": 39,
                "Ld": 39,
                "Int": 29,
                "Cl": 35,
                "WP": 30,
                "Fel": 35,
            },
            "Gunnery Captain": {
                "M": 4,
                "WS": 54,
                "BS": 30,
                "S": 3,
                "T": 3,
                "W": 9,
                "I": 45,
                "A": 1,
                "Dex": 29,
                "Ld": 50,
                "Int": 29,
                "Cl": 30,
                "WP": 26,
                "Fel": 32,
            },
        },
    },
    statblock_class=read_lines(Path("tests/assets/soldiers.py").absolute()),
)

druidic_priest = StatBlockTestCase(
    beast="Druidic Priest",
    stats={
        "Advance Scheme": {
            "Level 1": {
                "M": 0,
                "WS": 0,
                "BS": 0,
                "S": 0,
                "T": 0,
                "W": 2,
                "I": 10,
                "A": 0,
                "Dex": 0,
                "Ld": 0,
                "Int": 0,
                "Cl": 0,
                "WP": 10,
                "Fel": 0,
            },
            "Level 2": {
                "M": 0,
                "WS": 10,
                "BS": 10,
                "S": 1,
                "T": 1,
                "W": 3,
                "I": 20,
                "A": 0,
                "Dex": 10,
                "Ld": 10,
                "Int": 10,
                "Cl": 10,
                "WP": 20,
                "Fel": 10,
            },
            "Level 3": {
                "M": 0,
                "WS": 10,
                "BS": 10,
                "S": 1,
                "T": 1,
                "W": 4,
                "I": 20,
                "A": 0,
                "Dex": 20,
                "Ld": 20,
                "Int": 30,
                "Cl": 20,
                "WP": 20,
                "Fel": 20,
            },
            "Level 4": {
                "M": 0,
                "WS": 10,
                "BS": 10,
                "S": 1,
                "T": 1,
                "W": 4,
                "I": 30,
                "A": 0,
                "Dex": 30,
                "Ld": 30,
                "Int": 30,
                "Cl": 30,
                "WP": 30,
                "Fel": 30,
            },
        },
    },
    statblock_class=[],
)
